version: "3.5"
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: kashunattsutesuto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gZCrsGx!Pa#p*TjZ
    volumes:
      - postgres-data:/data/db

volumes:
  postgres-data: